# train
train : False
type : simpo # dpo / simpo
model : llama3-8b # mistral-7b / llama3-8b
epoch : 1.0

# dpo config (llamafactory)
save_path : saves/${model}/${type}
yaml_path : examples/train_lora/${model}/${type}
avail_devices : 0,1
start : 8 #이 숫자부터 진행 
end : 8 # 이 숫자까지 진행

# simpo config (simpo)

# export
export : True
export_yaml_path : examples/merge_lora/${model}/${type}
model_path : models/${model}/${type}

# export config
epoch_list : [] # 중간 epoch eval할 경우 
last_ckpt : True # 훈련 종료 후 마지막 checkpoint eval할 경우
last_ckpt_epoch : 1 # 마지막 checkpoint eval할 경우 epoch

# eval
eval : True
judge_name : gpt-4o-2024-11-20
judge_device : 0
judge_device_2 : 0
parallel_eval : True

# evaluation metric config
mt_bench : False
evol_instruct : False
alpaca_eval : False
hhh : True

# delete
delete : True