# alpaca eval is
alpaca_eval_gpt4o:
  prompt_template: "alpaca_eval_gpt4/alpaca_eval.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4o-2024-11-20"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "ranking_parser"
  batch_size: 1
