
#objective: score, calculation, figure
objective: 'calculation'

#score config
#score_method: sft, dpo, st, nv, rouge
score_method: sft
dataset: ultra
alias: 3ep
score_input_path: ../results/datasets/sft_ultra_e.jsonl
#if you use sft or dpo, you should set model_name, model_alias, start_idx
model_name: 01choco/LLaMA-UltraFeedback-SFT-3-Full
model_alias: LLaMA-UltraFeedback-SFT-3-Full
start_idx: 1 #1부터 시작
end_idx: 100000
score_output_path: ../results/score_data/${score_method}_${dataset}_${alias}.jsonl


#calculation config
#var_method: proxy (proxy-response), comb (response combination, score method should be st, nv)
#corr_method: cosine, pearson, pearson-minmax, kendall, kl
#rating: fine-grained, helpfulness
cal_input_path: ../results/score_data/${score_method}_${dataset}_${alias}.jsonl
var_method: proxy
corr_method: cosine
rating: fine-grained
cal_output_path: ../results/${score_method}_${dataset}_${alias}_${var_method}_${corr_method}_${rating}.jsonl

#figure config
fig_input_path: ../results/score_data/${score_method}_${dataset}_${alias}_${var_method}_${corr_method}_${rating}.jsonl
title: ${score_method} / ${dataset} / ${alias} / ${var_method} / ${corr_method}
min_cosine_similarity: 0
max_cosine_similarity: 0.9
fig_output_path: ../results/png/${score_method}_${dataset}_${alias}_${var_method}_${corr_method}.png